origin_sub_path: ''
ocr_sub_path: ''
origin_audio_path: ''
ocr_audio_path: ''
same_rate: 0.5
distance_string_rate: 0.8
distance_string_character: 2
soft_combine_rate: 0.8
framerate: 23.976023976023978
frame_distance: 3
apply_mode: comment
comment_timed_sub: true
comment_ocr_sub: true
quit_split_line_section: false
is_using_sushi: true
is_use_sign_timed: true
is_cmt_sign_timed: true
is_use_sign_ocr: true
is_cmt_sign_ocr: true
is_sync_sign_ocr: false
frame_range: 150
sample_shift_range: 5
output_filename: output.ass
punctuation: '].!?;,-'
color: red__purple__blue__yellow__green
ass_sign_tags: pos__move__org__clip__t
characters: "đóòỏõọôốồổỗộơớờởỡợáàảãạâấầẩẫậăắằẳẵặêếềểễệéèẻẽẹúùủũụưứừửữựíìỉĩịýỳỷỹỵĐÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶÊẾỀỂỄỆÉÈẺẼẸÚÙỦŨỤƯỨỪỬỮỰÍÌỈĨỊÝỲỶỸỴ"

Tooltip:
  origin_sub_path: "Location of timed subtitle."
  ocr_sub_path: "Location of ocr subtitle"
  origin_audio_path: "Location of audio/video which has timed subtitle"
  ocr_audio_path: "Location of audio/video which has ocr subtitle"
  output_filename: "Output file name, default location is in the same folder of program."
  is_using_sushi: "Check if you transfer subtitles from 2 different version (eg. BD vs TVs) or you not sure 2 video has same audio."
  is_use_sign_timed: "Add sign from timed_sub"
  is_cmt_sign_timed: "Comment sign from timed_sub"
  is_use_sign_ocr: "Add sign from timed_sub"
  is_cmt_sign_ocr: "Comment sign from ocr_sub"
  is_sync_sign_ocr: "[Experimental] compare multi frames between 2 video to shift properly"
  extend_function: "These options bellow only works if you choose shift signs. Tool will search structural_similarity around starter of each sign and shift automaticaly."
  frame_range: "Range of frames that tool search around. Increase it if TVs and BD got big different."
  sample_shift_range: "Number of frames tool use as sample for searching shift time. Increase it for more accurate."
  comment_timed_sub: "Choose to comment lines that only appear in timed subtitle. Default: True"
  comment_ocr_sub: "Choose to comment lines that only appear in ocr subtitle. Default: True"
  same_rate: "Ratio of same time between 2 lines. Default: 0.7"
  distance_string_character: "Check if 2 text lines from ocr are the same. Count per characters. Default: 2"
  distance_string_rate: "Check if 2 text lines from ocr are the same. Count as ratio. Default: 0.8"
  framerate: "Frame rate of video. Default: 24000/1001"
  frame_distance: "Check 2 lines has same time or not. Default: 24000/1001"